name: clickdoc1
description: "ClickDoc Flutter Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2

  # Firebase (aligned versions)
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: any
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.10

  # Google Sign-In (compatible)
  google_sign_in: ^6.1.6

  flutter_local_notifications: ^17.0.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  geolocator: ^10.1.0
  background_locator_2: ^2.0.6
  google_maps_flutter: any
  shared_preferences: ^2.2.3

  # Geo queries
  geoflutterfire2: ^2.3.15

  record: any
  path_provider: any
  url_launcher: any
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  just_audio: ^0.9.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/medical-assistance.png
    - assets/symptom_department_map.json