// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdsL27iAvG0Z17c7GHKf_qRDmEM6ZprmA',
    appId: '1:946830288694:web:0eafa052bd5d62e72a3597',
    messagingSenderId: '946830288694',
    projectId: 'clickdoc-7a312',
    authDomain: 'clickdoc-7a312.firebaseapp.com',
    storageBucket: 'clickdoc-7a312.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWYKXYGQMAKaLpBhIZBoK-xeYEyHe0RBc',
    appId: '1:946830288694:android:cdca8f57c07267c12a3597',
    messagingSenderId: '946830288694',
    projectId: 'clickdoc-7a312',
    storageBucket: 'clickdoc-7a312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwE5CS2PLuGaXnvxBL-dYnsqgM0Ni1sk8',
    appId: '1:946830288694:ios:f3878c1988be77ca2a3597',
    messagingSenderId: '946830288694',
    projectId: 'clickdoc-7a312',
    storageBucket: 'clickdoc-7a312.firebasestorage.app',
    androidClientId: '946830288694-js09vqap18umq6sn3a9ql32nli5vakfh.apps.googleusercontent.com',
    iosClientId: '946830288694-6c1jvp36q9cbteu3982i48psgp06i618.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickdoc1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwE5CS2PLuGaXnvxBL-dYnsqgM0Ni1sk8',
    appId: '1:946830288694:ios:f3878c1988be77ca2a3597',
    messagingSenderId: '946830288694',
    projectId: 'clickdoc-7a312',
    storageBucket: 'clickdoc-7a312.firebasestorage.app',
    androidClientId: '946830288694-js09vqap18umq6sn3a9ql32nli5vakfh.apps.googleusercontent.com',
    iosClientId: '946830288694-6c1jvp36q9cbteu3982i48psgp06i618.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickdoc1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdsL27iAvG0Z17c7GHKf_qRDmEM6ZprmA',
    appId: '1:946830288694:web:a798505466383a6b2a3597',
    messagingSenderId: '946830288694',
    projectId: 'clickdoc-7a312',
    authDomain: 'clickdoc-7a312.firebaseapp.com',
    storageBucket: 'clickdoc-7a312.firebasestorage.app',
  );
}
